# Generated by Django 4.1.1 on 2023-03-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='additional_data',
            field=models.TextField(blank=True, verbose_name='About you'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=75, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, verbose_name='Date of birth'),
        ),
    ]
