# Generated by Django 4.1.1 on 2023-04-04 22:56

from django.db import migrations, models
import rrp.models


class Migration(migrations.Migration):

    dependencies = [
        ('rrp', '0002_predictionresult_json_file_predictionresult_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionresult',
            name='json_file',
            field=models.FileField(blank=True, null=True, upload_to=rrp.models.user_directory_path_json, verbose_name='JSON File'),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=rrp.models.user_directory_path_pdf, verbose_name='PDF File'),
        ),
    ]
